### ISSUE TITLE
uc_update: Value too old?

### ISSUE THREAD

**Issue by OmegaVVeapon** [deniszh/collectd-iostat-python#14]
I configured the plugin as such:

    <Module collectd_iostat_python>
        Path "/usr/bin/iostat"
        Interval 3
        Count 2
        Verbose false
        NiceNames true
        PluginName collectd_iostat_python
    </Module>
My collectd polling is set to 10 seconds
According to the README file:
`Interval * Count << Collectd.INTERVAL` 3 * 2 << 10

But it I keep getting errors from collectd claiming that the internal cache time for the `bytes_per_second-read` data is already the same as the one we're about to add.

> [2016-11-14 18:30:12] uc_update: Value too old: name = machine1/collectd_iostat_python-sda/bytes_per_second-read; value time = 1479148212.429; last cache update = 1479148212.429;

Any insight on what could be going wrong?

**Comment by deniszh** [comment]
Yes, maybe I should be more strict with that. "<<" doesn't mean just "less", it's "much less".
This plugin running "iostat" command twice internally, one time for normal statistics, another - for extended stats. That's why I put "Interval 2" and "Count 2" as default values for default (10 seconds) Collectd interval.
Let me fix README.

**Comment by deniszh** [comment]
Fixed.
