### ISSUE TITLE
Issue with interval documentation

### ISSUE THREAD

**Issue by vincentbernat** [deniszh/collectd-iostat-python#25]
Hey!

The documentation says:

> Please note that this plugin will take only last line of `iostat` output, so big `Count` numbers also have no sense, but `Count` needs to be more than `1` to get actual and not historical data. But please note that `2 * Interval * Count` should be less than `Collectd.INTERVAL`. Default `Collectd.INTERVAL` is 10 seconds, so default value of `Count=2` and `Interval=2` works quite well for me.

First, `iostat` commands are run in parallel, so I don't think the 2 multiplier applies. Second, the duration is `interval * (count - 1)` (as the first set of values are given immediately).

Now, if a user configures with `Count=2` and `Interval=2`, it will get a value every 2 seconds. It is unclear if that's what is expected. I would have expected that collectd's interval would be used (one value every 10 seconds). In my case, a smaller value makes no sense because the data is stored in Graphite, which will take one value every 10 seconds. We should either state in the documentation the interval specifies the period of the collection (when count is 2) or we should not provide `self.interval` to `register_read_callback` to use collectd configured interval instead.

**Comment by deniszh** [comment]
Hi @vincentbernat ,
> First, iostat commands are run in parallel, so I don't think the 2 multiplier applies. Second, the duration is interval * (count - 1) (as the first set of values are given immediately).

Well, you probably right - `2 * Interval * Count` should be replaced by `Interval * (Count-1)`

> I would have expected that collectd's interval would be used (one value every 10 seconds).

I didn't like idea to use exact `Collectd.INTERVAL` for iostat, because real interval will be bigger then 10 seconds and theoretically will miss collectd interval. IMO 2 seconds interval is quite good but nothing (except wrong documentation :) ) stopping you from configuring Interval=10 and count = 2
